### ISSUE TITLE
[Quest] Thelsamar Blood Sausages - Can't turn in the quest

### ISSUE THREAD

**Issue by Purownage** [cmangos/classic-db#170] opened 2018-03-17 15:54 UTC
Thelsamar Blood Sausages - Can't turn in the quest when completed, need to abandon quest when you have all items for it and then retake it and turn in.

**Comment by cala** [comment] 2019-01-14 13:21
Tested again today, and I'm still unable to reproduce the issue. So, I'm closing this. Feel free to reopen it if you can provide more details.

**Closed by cala** 2019-01-14 13:21 UTC
