### ISSUE TITLE
Monument to Grom Hellscream

### ISSUE THREAD

**Issue by Phatcat** [cmangos/classic-db#5] opened 2016-10-22 00:06 UTC
https://youtu.be/UDQyEe06Q-M?t=19m34s

A few empty lines are missing on cmangos

(located in ashenvale)

**Comment by cala** [comment] 2016-11-18 10:21
Assigning myself.

**Comment by cala** [comment] 2016-11-23 21:08
Closed by https://github.com/cmangos/classic-db/commit/ae4da39678ba10f75fae970e3fb9b1fc0606ae03
Thank you!

**Closed** 2016-11-23 21:56 UTC

**Comment by cala** [comment] 2016-11-23 22:40
What am I thinking of? I say that I assign myself but forget to do so, and then, I say that the issue is closed, but I don't close it. Need holidays, maybe?

**Comment by Phatcat** [comment] 2016-11-23 23:10
Yes. Always more vacation =)
