### ISSUE TITLE
[mangos-classic] Cluck! quest broken

### ISSUE THREAD

**Issue by LordPsyan** [cmangos/classic-db#213] opened 2019-01-01 21:31 UTC
The quest "Cluck!" doesn't work as intended.

The way it should work:
1. /chicken until it turns green.
2. right click the chicken. Option to accept a quest to give feed should appear. Accept the quest
3. Buy feed from farmer and right click the chicken (this is how it works in 335)
4. complete the quest. Egg spawns.
4. Loot egg and get a pet.

How it currently works:
1. /chicken until it turns green.
2. right click chicken. Option a dialog that says you need special chicken feed. No option to accept quest. Even if you have the feed, you cannot complete.

**Comment by LordPsyan** [comment] 2019-01-02 16:52
Neither of those commits appear to have anything to do with this quest. I checked the DB for TBC and the quest is the same. Yes, it currently only is available to Alliance.

**Comment by killerwife** [comment] 2019-01-02 17:02
Please update this issue report with IDs for item and spell and quest.

**Comment by Muehe** [comment] 2019-01-02 17:08
@LordPsyan Those are just the commits I'm running right now, so the error is at least this old.

@killerwife It's all in the scripts enums I linked. There is no spell involved as far as I can see, only emotes. And factions.

**Comment by killerwife** [comment] 2019-01-02 17:13
The SD2 script has "if (!urand(0, 29))"
which means you have a random chance to complete it and RNG can screw you over easily.

**Comment by Muehe** [comment] 2019-01-02 17:15
That part works fine, the quest marker eventually appears over the chicken if you spam the emote enough. the player just can't accept the quest once it's there.

**Comment by killerwife** [comment] 2019-01-02 17:48
Are you guys sure the DB data is the same? This sounds like client thinks you can get quest but server says NOPE.

**Comment by Muehe** [comment] 2019-01-02 18:45
I can see two differences:

1. Classic has no `CompletedText` field which contains the text `Return to Chicken.` on Wotlk.
2. Wotlk has the value `42999` in all the `RewMaxRepValue` field.

Apart from that, they are the same, as are the scripts.

**Comment by killerwife** [comment] 2019-01-02 20:36
Someone has to investigate what packets are received by the server I'd say and what they do. I can't atm.

**Comment by Grz3s** [comment] 2019-01-02 22:16
i tested this quest yesterday.. and as prev said..it works fine in wotlk... for somehow ...it skips details in classic... checked `method = 2` in both...  my tests ended here koz i do not have classic client...
i didnt checked it for horde... but thats not an issue here... and its easy to fix. (from comments) 3.x.x added special npc in Brill ..so u can buy that special food

**Comment by cala** [comment] 2019-01-02 23:09
The issue is specific to Classic and to be more accurate to a certain combination of parameters for a quest in Classic. @Tobschinski investigated the parameters long ago but what happens core side in Classic for this specific set of parameters was not investigated. More : https://github.com/classicdb/database/issues/228

**Comment by Phatcat** [comment] 2019-01-03 18:30
It is indeed intended to be only for alliance in vanilla and TBC - Look at the elaborate lengths some of these commenters went to to actually obtain the pet as a horde;

https://web.archive.org/web/20070216132142/http://wow.allakhazam.com:80/db/quest.html?wquest=3861

It is also in the bradygames Master Guide

![image](https://user-images.githubusercontent.com/1907820/50654257-8acc6580-0f8c-11e9-8dc7-3db9f6e3b327.png)


> But there are numerous reports for the quest being attainable for Horde players prior to patch 3.1.

If you notice, all the 1.12 comments are made on the same day. This is indicating that the dating is off. Way off. What is the chance all those comments were actually made on the very same day? - I would personally not trust wowhead too much for vanilla stuff. This becomes especially apparent once you dig a little deeper and realize [William Saldean ](https://www.wowhead.com/npc=33996/william-saldean) wasn't added till 3.1, making the dating on the "Go to Brill (Yeah, Brill, not Westfall) Buy Special Chicken Feed from William Saldean" comment demonstrably wrong.

**Comment by Phatcat** [comment] 2019-01-11 17:42
> If you add the quest with a GM command on classic you get a blue question mark on the chicken and can turn in the quest.

The quest is not supposed to have a blue question mark, but a yellow one when you turn it in, even though the quest is repeatable;

https://www.youtube.com/watch?v=az8BNDNqzc4 (watch at 3:10)

https://www.youtube.com/watch?v=t6-OP22-aRE (watch at 0:22)

**Comment by cala** [comment] 2019-02-11 22:10
Closed by 
https://github.com/cmangos/mangos-classic/commit/185e72c04cc518064665fd66c7730aae69d6c468

**Closed by cala** 2019-02-11 22:10 UTC
